name: nlp_training
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - spacy=2.0.16
  - numpy=1.15.4
  - keras=2.2.4
  - matplotlib=3.0.1
  - pandas=0.23.4
  - nltk=3.3.0
  - scikit-learn
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator

