name: nlp-training
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - spacy
  - numpy
  - tensorflow-gpu=2.1.0
  - keras-gpu=2.3.1
  - matplotlib
  - pandas
  - nltk
  - scikit-learn
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator

